CREATE TABLE CUSTOMER
(
	Cid VARCHAR(15) NOT NULL,
	CFname VARCHAR(30) NOT NULL,
	CLname VARCHAR(30) NOT NULL,
	Email VARCHAR(30) DEFAULT NULL,
	Address VARCHAR(100) DEFAULT NULL,
	Credit_Card_Info VARCHAR(100) DEFAULT NULL,
	PRIMARY KEY(Cid)
);

CREATE TABLE TICKET
(
	Tid VARCHAR(15) NOT NULL,
	Price INT NOT NULL,
	Cid VARCHAR(15) NOT NULL,
	PRIMARY KEY(Tid),
	CONSTRAINT fk_ticket_cid
	FOREIGN KEY (Cid)
	REFERENCES CUSTOMER(Cid)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE ANIMAL_GUIDE
(
	AGid VARCHAR(15) NOT NULL,
	Zoo_Introduction TEXT NOT NULL,
	Updated_Year INT DEFAULT NULL,
	PRIMARY KEY(AGid)
);

CREATE TABLE ZOO
(
	Zid VARCHAR(15) NOT NULL,
	ZName VARCHAR(50) NOT NULL,
	Location VARCHAR(100) NOT NULL,
	Hours VARCHAR(100) NOT NULL,
	Contact VARCHAR(100) NOT NULL,
	AGid VARCHAR(15) NOT NULL,
	PRIMARY KEY(Zid),
	CONSTRAINT fk_zoo_AGid
	FOREIGN KEY (AGid)
	REFERENCES ANIMAL_GUIDE(AGid)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE EMPLOYEE
(
	Eid VARCHAR(15) NOT NULL,
	EFname VARCHAR(30) NOT NULL,
	ELname VARCHAR(30) NOT NULL,
	Phone_No VARCHAR(30) NOT NULL,
	Salary INT NOT NULL,
	Zid VARCHAR(15) NOT NULL,
	PRIMARY KEY(Eid),
	CONSTRAINT fk_emp_zid
	FOREIGN KEY (Zid)
	REFERENCES ZOO(Zid)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE ANIMAL_KIND
(
	AKid VARCHAR(15) NOT NULL,
	AName VARCHAR(30) NOT NULL,
	Physical_Characteristics TEXT NOT NULL,
	Zoo_Region VARCHAR(50) NOT NULL,
	Diet VARCHAR(30) NOT NULL,
	Population_Status VARCHAR(30) NOT NULL,
	PRIMARY KEY(AKid)
);

CREATE TABLE ANIMAL
(
	Aid VARCHAR(15) NOT NULL,
	Gender VARCHAR(10) DEFAULT NULL,
	Cage_Number INT NOT NULL,
	Feed_Time VARCHAR(30) NOT NULL,
	PRIMARY KEY(Aid),
	CONSTRAINT fk_ani_akid
	FOREIGN KEY (AKid)
	REFERENCES ANIMAL_KIND(AKid)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE ANIMAL_DETAIL
(
	ADid VARCHAR(15) NOT NULL,
	Height VARCHAR(10) DEFAULT NULL,
	Weight VARCHAR(10) DEFAULT NULL,
	Age INT DEFAULT NULL,
	Aid VARCHAR(15) NOT NULL,
	PRIMARY KEY(ADid),
	CONSTRAINT fk_ad_aid
	FOREIGN KEY (Aid)
	REFERENCES ANIMAL(Aid)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE GOES_TO
(
	Cid VARCHAR(15) NOT NULL,
	Zid VARCHAR(15) NOT NULL,
	PRIMARY KEY(Cid, Zid),
	CONSTRAINT fk1_gt_cid
	FOREIGN KEY (Cid)
	REFERENCES CUSTOMER(Cid)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT fk2_gt_zid
	FOREIGN KEY (Zid)
	REFERENCES ZOO(Zid)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE MANAGES
(
	Eid VARCHAR(15) NOT NULL,
	Tid VARCHAR(15) NOT NULL,
	PRIMARY KEY(Eid, Tid),
	CONSTRAINT fk1_man_eid
	FOREIGN KEY (Eid)
	REFERENCES EMPLOYEE(Eid)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT fk2_manages_tid
	FOREIGN KEY (Tid)
	REFERENCES TICKET(Tid)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE LOOKS_AFTER
(
	Eid VARCHAR(15) NOT NULL,
	Aid VARCHAR(15) NOT NULL,
	PRIMARY KEY(Eid, Aid),
	CONSTRAINT fk1_la_eid
	FOREIGN KEY (Eid)
	REFERENCES EMPLOYEE(Eid)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT fk2_looka_aid
	FOREIGN KEY (Aid)
	REFERENCES ANIMAL(Aid)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE CONTAINS
(
	AKid VARCHAR(15) NOT NULL,
	AGid VARCHAR(15) NOT NULL,
	PRIMARY KEY(AKid, AGid),
	CONSTRAINT fk1_cont_akid
	FOREIGN KEY (AKid)
	REFERENCES ANIMAL_KIND(AKid)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT fk2_contains_agid
	FOREIGN KEY (AGid)
	REFERENCES ANIMAL_GUIDE(AGid)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

ALTER TABLE ANIMAL_KIND
ADD CONSTRAINT chk_Animal_diet CHECK (Diet = 'Carnivore' OR Diet = 'Herbivore' OR 'Omnivore');

ALTER TABLE TICKET
ADD CONSTRAINT chk_ticket_price CHECK (Price >=8 AND Price <=25);
